"""VoicePet 运行时基础模块的公共导出"""

from .asr import (
    AsrConfigurationError,
    AsrError,
    AsrModelError,
    AsrModelState,
    AsrRuntimeStatus,
    AsrTranscriptionError,
    FasterWhisperTranscriptAdapter,
)
from .audio_input import (
    AudioCaptureService,
    AudioInputBackend,
    AudioSubscription,
    SoundDeviceInputBackend,
)
from .audio_session import CaptureService, VadAudioSession
from .audio_types import (
    AudioConfigurationError,
    AudioDeviceError,
    AudioError,
    AudioFormat,
    AudioFrameError,
    AudioOverflowError,
    CapturedFrame,
)
from .cancellation import CancellationSource, CancellationToken, CancelledError
from .config import (
    AppConfig,
    AsrConfig,
    AudioConfig,
    ConfigError,
    ConfigLoadResult,
    ConfigLoadStatus,
    ConfigStore,
    LlmConfig,
    PrivacyConfig,
    TtsConfig,
    UiConfig,
    WakeWordConfig,
    default_config_path,
)
from .config_application import ConfigApplicationMode, classify_config_change
from .coordinator import (
    AudioSession,
    Coordinator,
    TranscriptAdapter,
)
from .credentials import CredentialError, DpapiCredentialStore
from .diagnostics import (
    DiagnosticCheck,
    DiagnosticError,
    DiagnosticExporter,
    DiagnosticReport,
    DiagnosticResult,
    DiagnosticRunner,
    DiagnosticService,
    DiagnosticStatus,
)
from .event_bus import EventBus, Subscription
from .events import (
    ApprovalRequested,
    ConversationPhase,
    CorrelationId,
    ErrorSeverity,
    MemoryResultReady,
    RecordingStarted,
    RuntimeErrorEvent,
    SpeakRequested,
    StateChanged,
    TextDelta,
    TextInputSubmitted,
    TranscriptReady,
    TurnId,
    WakeCommandPending,
)
from .llm import (
    LlmAttachment,
    LlmCompleted,
    LlmConfigurationError,
    LlmError,
    LlmNetworkError,
    LlmProtocolError,
    LlmProvider,
    LlmRequest,
    LlmTextDelta,
    LlmToolCall,
    MockProvider,
    OpenAICompatibleProvider,
    OpenAIResponsesProvider,
    ResilientLlmProvider,
    ToolDefinition,
)
from .memory import (
    MemoryConfigurationError,
    MemoryError,
    MemoryPolicy,
    MemoryRecord,
    MemorySensitivity,
    MemoryStatus,
    MemoryStorageError,
    MemoryStore,
)
from .memory_context import MemoryContextAssembler
from .memory_data import MemoryDataError, MemoryDataManager
from .memory_intents import (
    MemoryIntent,
    MemoryIntentAction,
    MemoryIntentParser,
    MemoryOperation,
    MemoryOperationResult,
    MemoryOperationService,
)
from .network_resilience import (
    CircuitState,
    NetworkCircuitOpenError,
    NetworkResilience,
    NetworkResilienceSettings,
)
from .pet_packages import PetPackageError, PetPackageInstaller
from .runtime import RuntimeHost, RuntimeHostError, RuntimeServices
from .runtime_errors import runtime_error_event
from .runtime_factory import build_default_runtime
from .session_archive import (
    SessionArchiveError,
    SessionArchiveStore,
    SessionRecord,
    SessionTurnRecord,
    ShortTermSummaryRecord,
)
from .session_context import SessionContext
from .session_data import SessionDataManager
from .short_term_summary import ShortTermSummaryDraft
from .state_machine import ConversationStateMachine, InvalidTransition
from .structured_logging import (
    RuntimeEventLogger,
    StructuredLogError,
    StructuredLogStore,
)
from .tts import (
    AudioPlayer,
    EdgeTtsSynthesizer,
    EdgeTtsVoiceService,
    FallbackSpeechSynthesizer,
    ResilientSpeechSynthesizer,
    SentenceChunker,
    SpeechSynthesizer,
    SynthesizedAudio,
    TtsConfigurationError,
    TtsError,
    TtsNetworkError,
    TtsPlaybackError,
    TtsSynthesisError,
    TtsVoiceOption,
    WindowsMciAudioPlayer,
    WindowsSapiBackend,
    WindowsSapiSynthesizer,
    markdown_to_speech_text,
    split_speech_text,
)
from .turn_budget import TurnBudget, TurnBudgetExceededError, TurnBudgetLimits
from .vad import VoiceActivityDetector, WebRtcVadDetector
from .wake import (
    ActivationController,
    ActivationTarget,
    SherpaOnnxKeywordDetector,
    WakeConfigurationError,
    WakeDetectionError,
    WakeError,
    WakeRuntimeStatus,
    WakeWordDetector,
    WakeWordMonitor,
    WakeWordRuntimeService,
)
from .wake_models import (
    WakeDownloadProgress,
    WakeModelError,
    WakeModelFiles,
    WakeModelState,
    WakeModelStore,
)

__all__ = [
    "ActivationController",
    "ActivationTarget",
    "AppConfig",
    "ApprovalRequested",
    "AsrConfig",
    "AsrConfigurationError",
    "AsrError",
    "AsrModelError",
    "AsrModelState",
    "AsrRuntimeStatus",
    "AsrTranscriptionError",
    "AudioCaptureService",
    "AudioConfig",
    "AudioConfigurationError",
    "AudioDeviceError",
    "AudioError",
    "AudioFormat",
    "AudioFrameError",
    "AudioInputBackend",
    "AudioOverflowError",
    "AudioPlayer",
    "AudioSession",
    "AudioSubscription",
    "CancellationSource",
    "CancellationToken",
    "CancelledError",
    "CaptureService",
    "CapturedFrame",
    "CircuitState",
    "ConfigApplicationMode",
    "ConfigError",
    "ConfigLoadResult",
    "ConfigLoadStatus",
    "ConfigStore",
    "ConversationPhase",
    "ConversationStateMachine",
    "Coordinator",
    "CorrelationId",
    "CredentialError",
    "DiagnosticCheck",
    "DiagnosticError",
    "DiagnosticExporter",
    "DiagnosticReport",
    "DiagnosticResult",
    "DiagnosticRunner",
    "DiagnosticService",
    "DiagnosticStatus",
    "DpapiCredentialStore",
    "EdgeTtsSynthesizer",
    "EdgeTtsVoiceService",
    "ErrorSeverity",
    "EventBus",
    "FallbackSpeechSynthesizer",
    "FasterWhisperTranscriptAdapter",
    "InvalidTransition",
    "LlmAttachment",
    "LlmCompleted",
    "LlmConfig",
    "LlmConfigurationError",
    "LlmError",
    "LlmNetworkError",
    "LlmProtocolError",
    "LlmProvider",
    "LlmRequest",
    "LlmTextDelta",
    "LlmToolCall",
    "MemoryConfigurationError",
    "MemoryContextAssembler",
    "MemoryDataError",
    "MemoryDataManager",
    "MemoryError",
    "MemoryIntent",
    "MemoryIntentAction",
    "MemoryIntentParser",
    "MemoryOperation",
    "MemoryOperationResult",
    "MemoryOperationService",
    "MemoryPolicy",
    "MemoryRecord",
    "MemoryResultReady",
    "MemorySensitivity",
    "MemoryStatus",
    "MemoryStorageError",
    "MemoryStore",
    "MockProvider",
    "NetworkCircuitOpenError",
    "NetworkResilience",
    "NetworkResilienceSettings",
    "OpenAICompatibleProvider",
    "OpenAIResponsesProvider",
    "PetPackageError",
    "PetPackageInstaller",
    "PrivacyConfig",
    "RecordingStarted",
    "ResilientLlmProvider",
    "ResilientSpeechSynthesizer",
    "RuntimeErrorEvent",
    "RuntimeEventLogger",
    "RuntimeHost",
    "RuntimeHostError",
    "RuntimeServices",
    "SentenceChunker",
    "SessionArchiveError",
    "SessionArchiveStore",
    "SessionContext",
    "SessionDataManager",
    "SessionRecord",
    "SessionTurnRecord",
    "SherpaOnnxKeywordDetector",
    "ShortTermSummaryDraft",
    "ShortTermSummaryRecord",
    "SoundDeviceInputBackend",
    "SpeakRequested",
    "SpeechSynthesizer",
    "StateChanged",
    "StructuredLogError",
    "StructuredLogStore",
    "Subscription",
    "SynthesizedAudio",
    "TextDelta",
    "TextInputSubmitted",
    "ToolDefinition",
    "TranscriptAdapter",
    "TranscriptReady",
    "TtsConfig",
    "TtsConfigurationError",
    "TtsError",
    "TtsNetworkError",
    "TtsPlaybackError",
    "TtsSynthesisError",
    "TtsVoiceOption",
    "TurnBudget",
    "TurnBudgetExceededError",
    "TurnBudgetLimits",
    "TurnId",
    "UiConfig",
    "VadAudioSession",
    "VoiceActivityDetector",
    "WakeCommandPending",
    "WakeConfigurationError",
    "WakeDetectionError",
    "WakeDownloadProgress",
    "WakeError",
    "WakeModelError",
    "WakeModelFiles",
    "WakeModelState",
    "WakeModelStore",
    "WakeRuntimeStatus",
    "WakeWordConfig",
    "WakeWordDetector",
    "WakeWordMonitor",
    "WakeWordRuntimeService",
    "WebRtcVadDetector",
    "WindowsMciAudioPlayer",
    "WindowsSapiBackend",
    "WindowsSapiSynthesizer",
    "build_default_runtime",
    "classify_config_change",
    "default_config_path",
    "markdown_to_speech_text",
    "runtime_error_event",
    "split_speech_text",
]
